# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-sample',
                'doc_host': 'https://cbrew.github.io',
                'git_url': 'https://github.com/cbrew/nbdev-sample',
                'lib_path': 'nbdev_sample'},
  'syms': {'nbdev_sample.core': {'nbdev_sample.core.say_hello': ('core.html#say_hello', 'nbdev_sample/core.py')}}}
